repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]