"""AI coding tool metrics collection and analysis service.

Supports:
- GitHub Copilot (organization API)
- Cursor AI (log parsing)
- Claude Code / Aider (commit metadata detection)
"""

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import requests

from ..config import get_config_value
from ..db.models import AIUsageMetric
from ..db.repository import MetricStore

logger = logging.getLogger(__name__)


@dataclass
class AIToolSummary:
    tool: str
    total_suggestions_shown: int = 0
    total_suggestions_accepted: int = 0
    total_lines_accepted: int = 0
    active_users: int = 0
    acceptance_rate: float = 0.0
    total_cost_usd: float = 0.0
    daily_breakdown: list = field(default_factory=list)


@dataclass
class AIImpactAnalysis:
    ai_assisted_pr_count: int = 0
    non_ai_pr_count: int = 0
    ai_avg_cycle_time_hours: float = 0.0
    non_ai_avg_cycle_time_hours: float = 0.0
    ai_avg_review_time_hours: float = 0.0
    non_ai_avg_review_time_hours: float = 0.0
    ai_revert_rate: float = 0.0
    non_ai_revert_rate: float = 0.0
    productivity_change_pct: float = 0.0
    tools: list[AIToolSummary] = field(default_factory=list)


# --- GitHub Copilot ---

def collect_copilot_metrics(
    store: MetricStore,
    org: str,
    since: datetime,
    until: datetime,
    snapshot_id: Optional[int] = None,
) -> list[AIUsageMetric]:
    """Fetch GitHub Copilot usage metrics from the organization API."""
    token = get_config_value("GITHUB_TOKEN") or get_config_value("GITHUB_USER_TOKEN")
    if not token:
        logger.warning("No GitHub token configured for Copilot metrics")
        return []

    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    metrics = []
    since_str = since.strftime("%Y-%m-%d")
    until_str = until.strftime("%Y-%m-%d")

    try:
        url = f"https://api.github.com/orgs/{org}/copilot/usage"
        params = {"since": since_str, "until": until_str}
        resp = requests.get(url, headers=headers, params=params, timeout=30)

        if resp.status_code == 200:
            data = resp.json()
            for day in data:
                date_str = day.get("day", "")
                if not date_str:
                    continue

                metric = AIUsageMetric(
                    snapshot_id=snapshot_id,
                    tool="copilot",
                    date=datetime.fromisoformat(date_str).replace(tzinfo=timezone.utc),
                    suggestions_shown=day.get("total_suggestions_count", 0),
                    suggestions_accepted=day.get("total_acceptances_count", 0),
                    lines_suggested=day.get("total_lines_suggested", 0),
                    lines_accepted=day.get("total_lines_accepted", 0),
                    active_users=day.get("total_active_users", 0),
                    chat_sessions=day.get("total_chat_turns", 0),
                    metadata_={
                        "breakdown": day.get("breakdown", []),
                    },
                )
                store.ai_usage.add(metric)
                metrics.append(metric)

            store.commit()
            logger.info("Collected %d days of Copilot usage data", len(metrics))
        elif resp.status_code == 404:
            logger.info("Copilot usage API not available for org %s", org)
        else:
            logger.warning("Copilot API returned %d: %s", resp.status_code, resp.text[:200])

    except Exception as e:
        logger.error("Error fetching Copilot metrics: %s", e)

    return metrics


# --- AI Commit Detection ---

AI_COMMIT_PATTERNS = [
    re.compile(r"(?i)co-authored-by:.*copilot", re.MULTILINE),
    re.compile(r"(?i)co-authored-by:.*\bcursor\b", re.MULTILINE),
    re.compile(r"(?i)co-authored-by:.*\bclaude\b", re.MULTILINE),
    re.compile(r"(?i)co-authored-by:.*\baider\b", re.MULTILINE),
    re.compile(r"(?i)generated by (copilot|cursor|claude|aider|ai)"),
    re.compile(r"(?i)\[ai[-\s]generated\]"),
    re.compile(r"(?i)^aider:", re.MULTILINE),
]

AI_BOT_AUTHORS = {
    "github-actions[bot]", "dependabot[bot]", "renovate[bot]",
    "copilot", "cursor-ai", "claude-code",
}


def detect_ai_tool_from_pr(title: str, labels: list, body: str = "") -> Optional[str]:
    """Detect which AI tool was used based on PR metadata."""
    text = f"{title} {body}".lower()
    label_text = " ".join(l.lower() for l in labels)

    if "copilot" in text or "copilot" in label_text:
        return "copilot"
    if "cursor" in text or "cursor" in label_text:
        return "cursor"
    if "claude" in text or "claude code" in text or "claude" in label_text:
        return "claude_code"
    if "aider" in text or "aider" in label_text:
        return "aider"
    if "ai-generated" in label_text or "ai generated" in text:
        return "unknown_ai"
    return None


# --- Impact Analysis ---

def compute_ai_impact(store: MetricStore, start: datetime, end: datetime) -> AIImpactAnalysis:
    """Compare metrics between AI-assisted and non-AI PRs."""
    all_prs = store.pull_requests.get_merged_by_period(start, end)

    ai_prs = [p for p in all_prs if p.is_ai_generated]
    non_ai_prs = [p for p in all_prs if not p.is_ai_generated]

    def avg(values):
        return sum(values) / len(values) if values else 0

    ai_cycle = avg([p.cycle_time_hours for p in ai_prs if p.cycle_time_hours])
    non_ai_cycle = avg([p.cycle_time_hours for p in non_ai_prs if p.cycle_time_hours])

    ai_review = avg([p.time_to_first_review_hours for p in ai_prs if p.time_to_first_review_hours])
    non_ai_review = avg([p.time_to_first_review_hours for p in non_ai_prs if p.time_to_first_review_hours])

    ai_reverts = sum(1 for p in ai_prs if p.is_revert) / max(len(ai_prs), 1)
    non_ai_reverts = sum(1 for p in non_ai_prs if p.is_revert) / max(len(non_ai_prs), 1)

    prod_change = 0
    if non_ai_cycle > 0 and ai_cycle > 0:
        prod_change = ((non_ai_cycle - ai_cycle) / non_ai_cycle) * 100

    # Tool summaries
    ai_usage = store.ai_usage.get_summary(start, end)
    tools = []
    for row in ai_usage:
        accepted = row.total_accepted or 0
        shown = row.total_shown or 0
        tools.append(AIToolSummary(
            tool=row.tool,
            total_suggestions_shown=shown,
            total_suggestions_accepted=accepted,
            total_lines_accepted=row.total_lines or 0,
            active_users=row.peak_users or 0,
            acceptance_rate=accepted / shown if shown > 0 else 0,
            total_cost_usd=row.total_cost or 0,
        ))

    return AIImpactAnalysis(
        ai_assisted_pr_count=len(ai_prs),
        non_ai_pr_count=len(non_ai_prs),
        ai_avg_cycle_time_hours=ai_cycle,
        non_ai_avg_cycle_time_hours=non_ai_cycle,
        ai_avg_review_time_hours=ai_review,
        non_ai_avg_review_time_hours=non_ai_review,
        ai_revert_rate=ai_reverts,
        non_ai_revert_rate=non_ai_reverts,
        productivity_change_pct=prod_change,
        tools=tools,
    )
